apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: deploy-gestion
  labels:
    app: gestion
  name: gestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion
  strategy: {}
  template:
    metadata:
      labels:
        app: gestion
    spec:
      containers:
      - image: wissemlallahem/projet-test:development.20
        name: projet-test
        resources: {}
status: {}

